name: Update Notion Daily

on:
  schedule:
    - cron: '0 23 * * *'  # 每天 UTC 23:00，台灣時間早上 7:00 執行
  workflow_dispatch:

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install notion-client

      - name: Run main script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: python main.py
